name: Publish package
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Startup
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish and package
        run: ./gradlew build publish
        env:
          REPO_USERNAME: github-deploy
          REPO_PASSWORD: ${{ secrets.DEPLOY_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ProxyTransport
          path: build/libs/ProxyTransport.jar
